#!/bin/sh

#some more modding

bin/iconbutton 150 510 75 75 37  1 'mpc prev' & 
bin/iconbutton 243 510 75 75 37  0 'mpc seek -00:00:10' &
bin/iconbutton 429 510 75 75 37  0 'mpc seek +00:00:10' &
bin/iconbutton 522 510 75 75 37  1 'mpc next' & 
bin/iconbutton 150 600 112 112 52  3 'sudo reboot' & 
bin/iconbutton 150 727 112 112 52  4 'sudo poweroff' & 
bin/iconbutton 150 855 112 112 52  2 'pkill -u liquidcat' &

#these are the info widgets which display some data, thats it

bin/infowidget 540 315 150 75 34 2 'echo $(cat /sys/class/power_supply/BAT0/capacity)' &                      
bin/infowidget 540 150 315 150 75 0 'date +%H:%M' &                       
bin/infowidget 277 600 225 75 27 2 'echo " "$(ifstat | grep wlp3s0 | tr -s " " | cut -d " " -f6 | sed "s/K/000/g" | numfmt --to=iec-i)"B/s"' &  
bin/infowidget 277 697 225 75 27 4 'echo " "$(ifstat | grep wlp3s0 | tr -s " " | cut -d " " -f8 | sed "s/K/000/g" | numfmt --to=iec-i)"B/s"' &  
bin/infowidget 277 795 225 75 27 3 'echo " "$(top -bn 2 -d 0.01 | grep "^%Cpu" | tail -n 1 | gawk -f cpu.awk)"%"' &       
bin/infowidget 277 892 225 75 27 3 'echo " "$(./meminfo.sh)"B"' &                      
